### VARIABLES
@id = PUT-aaa

### GET all users
GET http://localhost:8080/api/casso/maintenance/users

### GET user by id
GET http://localhost:8080/api/casso/maintenance/users/{{id}}

### POST creete new user
POST http://localhost:8080/api/casso/maintenance/users
Content-Type: application/json

{
  "id": "PUT-aaa",
  "name": "Route Runner",
  "login": "Runner",
  "password": "BeBe3p-@!#"
}

### PUT update existing user
PUT http://localhost:8080/api/casso/maintenance/users
Content-Type: application/json

{
  "id": "PUT-aaa",
  "name": "CCCx",
  "login": "AAA",
  "password": "AAA"
}

### DELETE existing user
DELETE http://localhost:8080/api/casso/maintenance/users/{{id}}






